name: weather_app
description: A Flutter weather app using MVC architecture
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  intl: ^0.19.0
  dio: ^5.4.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  geolocator: ^10.1.0
  permission_handler: ^11.3.0
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

#  assets:
#    - assets/images/
#    - assets/icons/weather/